require 'rake'
require 'rspec/core/rake_task'
require 'yaml'

task :spec    => 'spec:all'
task :default => :spec

properties = YAML.load_file('/var/lib/jenkins/workspace/ansible-callback-web/spec/properties.yml')


namespace :spec do
  task :all => properties.keys.map {|key| 'spec:' + key.split('.')[0] }
  properties.keys.each do |key|
    desc "Run serverspec to #{key}"
    RSpec::Core::RakeTask.new(key.split('.')[0].to_sym) do |t|
      ENV['TARGET_HOST'] = key
      t.pattern = 'roles/{' + properties[key][:roles].join(',') + '}/*_spec.rb'
    end 
  end
end
